name: Build and Release APK

on:
  push:
    branches:
      - marketpro
      - proeditor

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache de pacotes Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Configurar SDK do Android
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools: 30.0.3
          cmake-version: 3.10.2

      - name: Conceder permissão de execução para Gradlew
        run: chmod +x ./gradlew

      - name: Configurar variáveis de ambiente para assinatura
        run: |
          echo "ANDROID_KEYSTORE_BASE64=${{ secrets.ANDROID_KEYSTORE_BASE64 }}" >> $GITHUB_ENV
          echo "ANDROID_KEYSTORE_PASSWORD=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "ANDROID_KEY_ALIAS=${{ secrets.ANDROID_KEY_ALIAS }}" >> $GITHUB_ENV
          echo "ANDROID_KEY_PASSWORD=${{ secrets.ANDROID_KEY_PASSWORD }}" >> $GITHUB_ENV

      - name: Decodificar e armazenar o arquivo JKS
        run: |
          mkdir -p ~/.android
          echo $ANDROID_KEYSTORE_BASE64 | base64 --decode > ~/.android/keystore.jks
        shell: bash

      - name: Verificar se o arquivo JKS foi criado
        run: ls -la ~/.android/keystore.jks

      - name: Compilar APK de Release
        run: ./gradlew assembleRelease -Pandroid.injected.signing.store.file=$HOME/.android/keystore.jks -Pandroid.injected.signing.store.password=${{ secrets.ANDROID_KEYSTORE_PASSWORD }} -Pandroid.injected.signing.key.alias=${{ secrets.ANDROID_KEY_ALIAS }} -Pandroid.injected.signing.key.password=${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Obter mensagem do commit
        id: get_commit_message
        run: echo "COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV

      - name: Criar Release
        id: create_release
        run: |
          response=$(curl -s -X POST https://api.github.com/repos/${{ github.repository }}/releases \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"tag_name\": \"release-${{ github.sha }}\", \"name\": \"${{ env.COMMIT_MESSAGE }} - ${{ github.ref_name }}\", \"draft\": false, \"prerelease\": false}")
          echo "RELEASE_ID=$(echo $response | jq -r '.id')" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fazer upload do APK de Release para a Release
        run: |
          curl -s -X POST ${{ env.RELEASE_UPLOAD_URL }} \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/vnd.android.package-archive" \
            -H "Accept: application/vnd.github.v3+json" \
            --data-binary @app/build/outputs/apk/release/app-release.apk \
            -o response.json
          echo "Upload concluído com sucesso."
        env:
          RELEASE_UPLOAD_URL: ${{ steps.create_release.outputs.upload_url }}
